version: '3.8'
services:
  app:
    image: myapp:latest
    environment:
      - NODE_ENV=ENV_TYPE
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
